# -*- coding: utf-8 -*-
"""MD5String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Kuo1Mp7JBcMJlKQ-OMVIapGHQbXoqaS
"""

import hashlib

def main(): 

    text = "Hello World!"
    textUtf8 = text.encode("utf-8")

    hash = hashlib.md5( textUtf8 )
    hexa = hash.hexdigest()

    print ( hexa )

    return

main()